version: '3'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile_app
    ports:
      - "127.0.0.1:5000:5000"
    deploy:
      resources:
        limits:
          pids: 6

  tester:
    container_name: tester
    build:
      context: ./tests
      dockerfile: Dockerfile_tester
    env_file:
      - ./tests/.env
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3222:22"
    depends_on:
      - app
    deploy:
      resources:
        limits:
          pids: 12 # При значении 6 не запускаются тесты