FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y \ 
    git=1:2.34.1-1ubuntu1 \
    python3.11=3.11.0~rc1-1~22.04 \
    python3-pip=22.0.2+dfsg-1  \
    python2.7=2.7.18-13ubuntu1.2 \
    openssh-server=1:8.9p1-3ubuntu0.7 \
    wget=1.21.2-2ubuntu1

WORKDIR /tester

RUN git clone https://github.com/moevm/devops-examples.git && \
    touch ./devops-examples/EXAMPLE_APP/__init__.py && \
    mv ./devops-examples/EXAMPLE_APP . && \
    rm -r ./devops-examples

RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

COPY ./ssh_keys/id_rsa.pub /root/.ssh/authorized_keys

COPY . .

RUN wget -P style https://svn.python.org/projects/python/trunk/Tools/scripts/pindent.py && \
    patch -l ./EXAMPLE_APP/bussiness_logic.py ./static/filepatch.patch && \
    pip3 install -r requirements.txt

ENTRYPOINT [ "bash", "start.sh" ]