FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y \ 
    git=1:2.34.1-1ubuntu1 \
    python3.11=3.11.0~rc1-1~22.04 \
    python3-pip=22.0.2+dfsg-1 

RUN git clone https://github.com/moevm/devops-examples.git && \
    cd devops-examples && \
    rm -r `ls | grep -v "EXAMPLE_APP"`

WORKDIR /devops-examples/EXAMPLE_APP

COPY filepatch.patch .

RUN patch -l main.py filepatch.patch

COPY requirements.txt .

RUN pip3 install -r requirements.txt

ENTRYPOINT [ "python3", "main.py" ]
